# Generated by Django 3.1.7 on 2021-05-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
